package beans;
// Generated Dec 23, 2020 12:16:54 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

    private Integer idorder;
    private Retailers retailers;
    private User user;
    private Date orderDate;
    private BigDecimal orderAmount;
    private Date dateCreated;
    private Date lastUpdated;

    public Orders() {
    }

    public Orders(Retailers retailers, User user, Date orderDate, BigDecimal orderAmount, Date dateCreated, Date lastUpdated) {
        this.retailers = retailers;
        this.user = user;
        this.orderDate = orderDate;
        this.orderAmount = orderAmount;
        this.dateCreated = dateCreated;
        this.lastUpdated = lastUpdated;
    }

    public Integer getIdorder() {
        return this.idorder;
    }

    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }

    public Retailers getRetailers() {
        return this.retailers;
    }

    public void setRetailers(Retailers retailers) {
        this.retailers = retailers;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public BigDecimal getOrderAmount() {
        return this.orderAmount;
    }

    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
