package beans;
// Generated Dec 23, 2020 12:16:54 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Retailers generated by hbm2java
 */
public class Retailers implements java.io.Serializable {

    public String getRetailerImage() {
        return retailerImage;
    }

    public void setRetailerImage(String retailerImage) {
        this.retailerImage = retailerImage;
    }

    private Integer idretailers;
    private String retailerName;
    private String retailerImage;
    private String email;
    private String phone;
    private String address;
    private boolean available;
    private Date dateCraeted;
    private Date lastUpdated;

    public Retailers() {
    }

    public Retailers(String retailerName, String email, String phone, String address, boolean available, Date dateCraeted, Date lastUpdated) {
        this.retailerName = retailerName;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.available = available;
        this.dateCraeted = dateCraeted;
        this.lastUpdated = lastUpdated;
    }

    public Integer getIdretailers() {
        return this.idretailers;
    }

    public void setIdretailers(Integer idretailers) {
        this.idretailers = idretailers;
    }

    public String getRetailerName() {
        return this.retailerName;
    }

    public void setRetailerName(String retailerName) {
        this.retailerName = retailerName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public boolean getAvailable() {
        return this.available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    public Date getDateCraeted() {
        return this.dateCraeted;
    }

    public void setDateCraeted(Date dateCraeted) {
        this.dateCraeted = dateCraeted;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
