package beans;
// Generated Dec 23, 2020 12:16:54 AM by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer iduserRole;
     private Role role;
     private User user;

    public UserRole() {
    }

    public UserRole(Role role, User user) {
       this.role = role;
       this.user = user;
    }
   
    public Integer getIduserRole() {
        return this.iduserRole;
    }
    
    public void setIduserRole(Integer iduserRole) {
        this.iduserRole = iduserRole;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


